sudo: false
language: c

install:
    - echo "CONFIG_TARGET_pistachio=y" > ./.config
    - echo "CONFIG_TARGET_pistachio_marduk_marduk_cc2520=y" >> ./.config

script:
    - make defconfig
    - ./.travis.sh
